paths:
  wildtype: "reference/nylB_wildtype.fasta"
  variants: "reference/nylB_variants.fasta"
  pre_selection: "data/simulated/pre_selection.fastq"
  post_selection: "data/simulated/post_selection.fastq"
  individual_fastas: "data/simulated/individual"

simulation:
  n_variants: 10
  n_mutations: 15
  seed: 42
  base_quantity: "200x"
  winner_quantity: "500x"
  winners:
    - 2
    - 5
    - 8

samples:
  - pre_selection
  - post_selection