name: nylb-pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - biopython
  - pyyaml
  - pysam
  - pandas
  - snakemake
  - samtools
  - nanostat
  - porechop
  - minimap2
  - pytest
  - pip:
    - git+https://github.com/rrwick/Badread.git